### ISSUE TITLE
Syntax highlighting: "http://ffff{$param1}" not detect using param1

### ISSUE THREAD

**Issue by DisDis** [vtst/ow#21]
Plugin not detect parameters used in "http://...."
Eclipse tooltip: "Unused template parameter"

example:
/**
Button G+
@param? target
@param? socUrl
@param? cssClass
@param? link 
@param? title  
@param? desc 
@param? imgUrl 
@param? cssId
**/
{template .buttonGPlus}
<a {if $socUrl}href="https://m.google.com/app/plus/x/?v=compose&content={$link|escapeHtml}{if $title}{sp}{$title|escapeUri}{/if}{if $desc}{sp}{$desc|escapeUri}{/if}{if $imgUrl}{sp}{$imgUrl}{/if}"{/if}{sp}
   {if $cssId}id="{$cssId}"{/if}{sp}
   {if $target}target="_blank"{/if}{sp}
   {if $title}title="{$title}"{/if}{sp}
        class="{css social-network-ico} {css gplus-ico}{sp}{if $cssClass}{$cssClass}{/if}"
   soy-tn="common.ui.share.buttonGPlus">{msg desc="Google+"}Google+{/msg}</a>
{/template}

**Comment by vtst** [comment]
Thanks for the bug report.
1. Sorry, but I do not see the "http://fffff{$param1}" in the code example, did I miss something?
2. Which version of the plugin are you using? It seems that your issue might be the same as https://github.com/vtst/ow/issues/18. I fixed this issue in version 1.0.1 which was released yesterday. If you did not yet install this new version, you should give it a try, it may solve your problem.
Please keep me posted.

**Comment by DisDis** [comment]
1. This is a simple example
2. I used 1.0.1 plugin version, but issues 18 not fixed...Eclipse can not validated soy

**Comment by vtst** [comment]
I just investigated, and there was an error in the release process for the version 1.0.1.
So, I released version 1.02, where this problem is solved. Sorry for the mistake.
